apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
  labels:
    type: local
spec:
  storageClassName: mysqldb
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysqldb"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc3
spec:
  storageClassName: mysqldb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi