apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.49.5
  ports:
    - name: wordpress
      port: 5050
      targetPort: 5050
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
#          livenessProbe:
#            exec:
#              command:
#                - '/bin/sh -c pgrep php'
#            initialDelaySeconds: 10
#            periodSeconds: 5